### ISSUE TITLE
KeyError: 'family_source_id'

### ISSUE THREAD

**Issue by marypilataki** [Aavache/CAESynth#1]
Hello,

Thank you for sharing your work and for your clear presentation!

I came across an issue in line 238 ( and wherever 'family_source_id' is used as a key ):
KeyError: 'family_source_id'

Indeed, in the nsynth dataset default json metadata files there is not entry with 'family_source_id'. I undestand that this has to do with the timbre class. Did you maybe mean 'instrument_family' or 'instrument_source' or did you modify the metadata to include some additional entries? Also encountered something similar with key 'stage' in line 184 and modified the metadata myself to include e.g. stage: train.

Thanks again!
Mary

**Comment by Aavache** [comment]
Hi @marypilataki, thank you for your interest and raising the issue!. Sorry about this error, I had an additional script for arranging a metadata of `NSynth`. I will commit that script/notebook whenever I have some spare time since it requires some refactoring 

For the time being, you might be able to implement it yourself if you find it necessary right now. To do so, as explained in the paper, `family_source_id` would correspond to the pair combination of both columns `instrument_source` and `instrument_family` . The resulting number of classes is 28 and you can find the full list in the paper, below legend in figure 4. `Stage` corresponds to the data split, i.e. `train`,  `validation` and `test`, which was added in the csv as a new column I believe.

**Comment by marypilataki** [comment]
Hi @Aavache thank you very much for your response. I see, you clearly describe this in the paper, many thanks.
